management:
  endpoint:
    shutdown:
      enabled: true
    health:
#      show-details: always
      show-components: always
  info:
    git:
      mode: "full"
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: hello-actuator
    company: hi

logging:
  level:
    hello.controller: debug